# This file override .editorconfig
plugins = [
    "prettier-plugin-svelte"
]
trailingComma = "none"
svelteSortOrder = "options-scripts-markup-styles"
svelteAllowShorthand = false
bracketSameLine = false
svelteIndentScriptAndStyle = true
htmlWhitespaceSensitivity = "strict"
